### ISSUE TITLE
Config resetted sometimes

### ISSUE THREAD

**Issue by fralbo** [s-victor/TinyPedal#54] opened 2024-07-11 20:45 UTC
Hello,
That's now the 3rd time widget's config is completely reseted when I start TinyPedal.
All widget's are ON and stored at the left of the screen.
I saw there are some backups but they only contain 66ko of '0' !?!
I don't know how does it happen.
I use version 2.14.0 with LMU.
Here are my setting files.
[LMP2.json](https://github.com/user-attachments/files/16183293/LMP2.json)
[LMP2-backup 2024-07-05 14-51-56.json](https://github.com/user-attachments/files/16183298/LMP2-backup.2024-07-05.14-51-56.json)

**Comment by s-victor** [comment] 2024-07-12 04:09
Hi, thanks for reporting. The issue is likely happened when the APP tries to save preset the "last time", but somehow failed to save correctly. By default, the APP will retry up to 5 times if saving fails, and I would guess for some reason (probably system or CPU very busy) that all those 5 attempts failed.

I will try improve the saving system to avoid such issue in the coming days. Meanwhile you can manually make backups in case it happens again.

**Comment by s-victor** [comment] 2024-07-13 04:01
New improvements to saving system is included in `v2.15.1` update:
https://github.com/s-victor/TinyPedal/releases/tag/v2.15.1

Let me know if it helps.

**Comment by fralbo** [comment] 2024-07-13 06:34
Ok, thanks a lot.
If I well understand, changes we make on live are supposed to be saved on the fly on the current preset?

**Comment by s-victor** [comment] 2024-07-13 08:02
Correct. There is one exception, which the main config window position is only saved on APP exit (if position has changed).

**Comment by fralbo** [comment] 2024-07-19 15:11
Hello,
No more problems up to now.
Thanks a lot.

**Comment by s-victor** [comment] 2024-07-19 15:29
Thanks, I'll close the issue now.

**Closed by s-victor** 2024-07-19 15:29 UTC
Labels: bug, enhancement
